import type { User, Book, Conversation, Message, Order } from './types'

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'marko@email.com',
    name: 'Marko Petrović',
    avatar: '/avatars/marko.jpg',
    isBusiness: false,
    isVerified: true,
    city: 'Beograd',
    createdAt: new Date('2024-01-15'),
    walletBalance: 2500,
    freeBooksThisMonth: 1,
  },
  {
    id: 'user-2',
    email: 'knjizara@laguna.rs',
    name: 'Laguna Knjižara',
    avatar: '/avatars/laguna.jpg',
    isBusiness: true,
    isVerified: true,
    city: 'Beograd',
    createdAt: new Date('2023-06-01'),
    walletBalance: 150000,
    freeBooksThisMonth: 0,
  },
  {
    id: 'user-3',
    email: 'ana@email.com',
    name: 'Ana Jovanović',
    isBusiness: false,
    isVerified: false,
    city: 'Novi Sad',
    createdAt: new Date('2024-03-20'),
    walletBalance: 800,
    freeBooksThisMonth: 0,
  },
  {
    id: 'user-4',
    email: 'vulkan@knjizara.rs',
    name: 'Vulkan Izdavaštvo',
    avatar: '/avatars/vulkan.jpg',
    isBusiness: true,
    isVerified: true,
    city: 'Beograd',
    createdAt: new Date('2023-01-10'),
    walletBalance: 280000,
    freeBooksThisMonth: 0,
  },
  {
    id: 'user-5',
    email: 'jovan@email.com',
    name: 'Jovan Nikolić',
    isBusiness: false,
    isVerified: true,
    city: 'Niš',
    createdAt: new Date('2024-02-28'),
    walletBalance: 1200,
    freeBooksThisMonth: 2,
  },
]

export const mockBooks: Book[] = [
  {
    id: 'book-1',
    title: 'Na Drini ćuprija',
    author: 'Ivo Andrić',
    description: 'Remek-delo srpske književnosti, roman o mostu koji povezuje ljude i epohe. Očuvano izdanje iz 1990. godine.',
    condition: 'odlicno',
    price: 1200,
    isDonation: false,
    deliveryOption: 'both',
    paymentMethod: 'card',
    city: 'Beograd',
    images: ['/books/na-drini-cuprija.jpg'],
    sellerId: 'user-1',
    seller: mockUsers[0],
    createdAt: new Date('2024-12-01'),
    category: 'Klasici',
  },
  {
    id: 'book-2',
    title: 'Hazarski rečnik',
    author: 'Milorad Pavić',
    description: 'Muška verzija ovog jedinstvenog leksikonskog romana. Novo izdanje.',
    condition: 'novo',
    price: 2500,
    isDonation: false,
    deliveryOption: 'post',
    paymentMethod: 'card',
    city: 'Beograd',
    images: ['/books/hazarski-recnik.jpg'],
    sellerId: 'user-2',
    seller: mockUsers[1],
    createdAt: new Date('2024-12-10'),
    category: 'Fantastika',
  },
  {
    id: 'book-3',
    title: '1984',
    author: 'George Orwell',
    description: 'Prevod na srpski. Knjiga je u dobrom stanju sa blagim tragovima korišćenja.',
    condition: 'dobro',
    price: 0,
    isDonation: true,
    deliveryOption: 'personal',
    paymentMethod: 'cash',
    city: 'Novi Sad',
    images: ['/books/1984.jpg'],
    sellerId: 'user-3',
    seller: mockUsers[2],
    createdAt: new Date('2024-12-15'),
    category: 'Naučna fantastika',
  },
  {
    id: 'book-4',
    title: 'Mali princ',
    author: 'Antoine de Saint-Exupéry',
    description: 'Ilustrovano izdanje sa prelepim crtežima. Idealno za poklon.',
    condition: 'kao-novo',
    price: 1800,
    isDonation: false,
    deliveryOption: 'both',
    paymentMethod: 'card',
    city: 'Beograd',
    images: ['/books/mali-princ.jpg'],
    sellerId: 'user-4',
    seller: mockUsers[3],
    createdAt: new Date('2024-12-18'),
    category: 'Dečija literatura',
  },
  {
    id: 'book-5',
    title: 'Prokleta avlija',
    author: 'Ivo Andrić',
    description: 'Klasik srpske književnosti. Korišćeno izdanje u prihvatljivom stanju.',
    condition: 'prihvatljivo',
    price: 0,
    isDonation: true,
    deliveryOption: 'personal',
    paymentMethod: 'cash',
    city: 'Niš',
    images: ['/books/prokleta-avlija.jpg'],
    sellerId: 'user-5',
    seller: mockUsers[4],
    createdAt: new Date('2024-12-20'),
    category: 'Klasici',
  },
  {
    id: 'book-6',
    title: 'Derviš i smrt',
    author: 'Meša Selimović',
    description: 'Jedno od najznačajnijih dela jugoslovenske književnosti. Novo izdanje.',
    condition: 'novo',
    price: 2200,
    isDonation: false,
    deliveryOption: 'post',
    paymentMethod: 'card',
    city: 'Beograd',
    images: ['/books/dervis-i-smrt.jpg'],
    sellerId: 'user-2',
    seller: mockUsers[1],
    createdAt: new Date('2024-12-22'),
    category: 'Klasici',
  },
  {
    id: 'book-7',
    title: 'Harry Potter i Kamen mudrosti',
    author: 'J.K. Rowling',
    description: 'Srpski prevod, tvrdi povez. Odlično stanje.',
    condition: 'odlicno',
    price: 1500,
    isDonation: false,
    deliveryOption: 'both',
    paymentMethod: 'card',
    city: 'Novi Sad',
    images: ['/books/harry-potter.jpg'],
    sellerId: 'user-3',
    seller: mockUsers[2],
    createdAt: new Date('2024-12-25'),
    category: 'Fantastika',
  },
  {
    id: 'book-8',
    title: 'Zločin i kazna',
    author: 'Fjodor Dostojevski',
    description: 'Klasik ruske književnosti u novom prevodu. Kao novo.',
    condition: 'kao-novo',
    price: 1900,
    isDonation: false,
    deliveryOption: 'post',
    paymentMethod: 'card',
    city: 'Beograd',
    images: ['/books/zlocin-i-kazna.jpg'],
    sellerId: 'user-4',
    seller: mockUsers[3],
    createdAt: new Date('2024-12-28'),
    category: 'Klasici',
  },
  {
    id: 'book-9',
    title: 'Alisa u zemlji čuda',
    author: 'Lewis Carroll',
    description: 'Ilustrovano izdanje za decu. Poklanjam jer sam kupila duplikat.',
    condition: 'dobro',
    price: 0,
    isDonation: true,
    deliveryOption: 'personal',
    paymentMethod: 'cash',
    city: 'Beograd',
    images: ['/books/alisa.jpg'],
    sellerId: 'user-1',
    seller: mockUsers[0],
    createdAt: new Date('2024-12-30'),
    category: 'Dečija literatura',
  },
  {
    id: 'book-10',
    title: 'Autobiografija',
    author: 'Branislav Nušić',
    description: 'Humoristično delo velikog srpskog pisca. Retko izdanje.',
    condition: 'dobro',
    price: 800,
    isDonation: false,
    deliveryOption: 'both',
    paymentMethod: 'cash',
    city: 'Niš',
    images: ['/books/autobiografija.jpg'],
    sellerId: 'user-5',
    seller: mockUsers[4],
    createdAt: new Date('2025-01-02'),
    category: 'Humor',
  },
  {
    id: 'book-11',
    title: 'Seobe',
    author: 'Miloš Crnjanski',
    description: 'Monumentalno delo srpske književnosti. Novo izdanje sa predgovorom.',
    condition: 'novo',
    price: 2800,
    isDonation: false,
    deliveryOption: 'post',
    paymentMethod: 'card',
    city: 'Beograd',
    images: ['/books/seobe.jpg'],
    sellerId: 'user-2',
    seller: mockUsers[1],
    createdAt: new Date('2025-01-05'),
    category: 'Klasici',
  },
  {
    id: 'book-12',
    title: 'Sapiens: Kratka istorija čovečanstva',
    author: 'Yuval Noah Harari',
    description: 'Bestseler o istoriji ljudske vrste. Odlično očuvano.',
    condition: 'odlicno',
    price: 2100,
    isDonation: false,
    deliveryOption: 'both',
    paymentMethod: 'card',
    city: 'Beograd',
    images: ['/books/sapiens.jpg'],
    sellerId: 'user-1',
    seller: mockUsers[0],
    createdAt: new Date('2025-01-10'),
    category: 'Naučno-popularna',
  },
]

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    participants: [mockUsers[0], mockUsers[2]],
    bookId: 'book-3',
    book: mockBooks[2],
    lastMessage: {
      id: 'msg-1',
      conversationId: 'conv-1',
      senderId: 'user-3',
      content: 'Da, knjiga je još uvek dostupna. Možemo se naći sutra?',
      createdAt: new Date('2025-01-15T14:30:00'),
      read: false,
    },
    updatedAt: new Date('2025-01-15T14:30:00'),
  },
  {
    id: 'conv-2',
    participants: [mockUsers[0], mockUsers[3]],
    bookId: 'book-4',
    book: mockBooks[3],
    lastMessage: {
      id: 'msg-2',
      conversationId: 'conv-2',
      senderId: 'user-4',
      content: 'Hvala na kupovini! Pošiljka će biti poslata sutra.',
      createdAt: new Date('2025-01-14T10:15:00'),
      read: true,
    },
    updatedAt: new Date('2025-01-14T10:15:00'),
  },
]

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    conversationId: 'conv-1',
    senderId: 'user-1',
    content: 'Zdravo! Da li je knjiga 1984 još uvek dostupna?',
    createdAt: new Date('2025-01-15T14:00:00'),
    read: true,
  },
  {
    id: 'msg-2',
    conversationId: 'conv-1',
    senderId: 'user-3',
    content: 'Da, knjiga je još uvek dostupna. Možemo se naći sutra?',
    createdAt: new Date('2025-01-15T14:30:00'),
    read: false,
  },
  {
    id: 'msg-3',
    conversationId: 'conv-2',
    senderId: 'user-1',
    content: 'Želim da kupim Mali princ. Da li je moguća dostava?',
    createdAt: new Date('2025-01-14T09:00:00'),
    read: true,
  },
  {
    id: 'msg-4',
    conversationId: 'conv-2',
    senderId: 'user-4',
    content: 'Naravno! Dostava je moguća preko Post Express-a.',
    createdAt: new Date('2025-01-14T09:30:00'),
    read: true,
  },
  {
    id: 'msg-5',
    conversationId: 'conv-2',
    senderId: 'user-1',
    content: 'Odlično, naručujem!',
    createdAt: new Date('2025-01-14T10:00:00'),
    read: true,
  },
  {
    id: 'msg-6',
    conversationId: 'conv-2',
    senderId: 'user-4',
    content: 'Hvala na kupovini! Pošiljka će biti poslata sutra.',
    createdAt: new Date('2025-01-14T10:15:00'),
    read: true,
  },
]

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    bookId: 'book-4',
    book: mockBooks[3],
    buyerId: 'user-1',
    buyer: mockUsers[0],
    sellerId: 'user-4',
    seller: mockUsers[3],
    status: 'shipped',
    totalAmount: 2150,
    shippingFee: 350,
    platformFee: 180,
    donationAmount: 0,
    trackingNumber: 'PE123456789RS',
    createdAt: new Date('2025-01-14'),
  },
  {
    id: 'order-2',
    bookId: 'book-6',
    book: mockBooks[5],
    buyerId: 'user-3',
    buyer: mockUsers[2],
    sellerId: 'user-2',
    seller: mockUsers[1],
    status: 'delivered',
    totalAmount: 2550,
    shippingFee: 350,
    platformFee: 220,
    donationAmount: 100,
    trackingNumber: 'PE987654321RS',
    deliveredAt: new Date('2025-01-12'),
    disputeDeadline: new Date('2025-01-14'),
    createdAt: new Date('2025-01-10'),
  },
]

export const categories = [
  { id: 'classics', name: 'Klasici', nameCyrillic: 'Класици', icon: 'BookOpen' },
  { id: 'fantasy', name: 'Fantastika', nameCyrillic: 'Фантастика', icon: 'Sparkles' },
  { id: 'scifi', name: 'Naučna fantastika', nameCyrillic: 'Научна фантастика', icon: 'Rocket' },
  { id: 'children', name: 'Dečija literatura', nameCyrillic: 'Дечија литература', icon: 'Baby' },
  { id: 'science', name: 'Naučno-popularna', nameCyrillic: 'Научно-популарна', icon: 'Microscope' },
  { id: 'humor', name: 'Humor', nameCyrillic: 'Хумор', icon: 'Laugh' },
  { id: 'poetry', name: 'Poezija', nameCyrillic: 'Поезија', icon: 'Feather' },
  { id: 'biography', name: 'Biografije', nameCyrillic: 'Биографије', icon: 'User' },
]

export const cities = [
  'Ada',
  'Aleksandrovac',
  'Aleksinac',
  'Alibunar',
  'Apatin',
  'Aranđelovac',
  'Arilje',
  'Babušnica',
  'Bač',
  'Bačka Palanka',
  'Bačka Topola',
  'Bački Petrovac',
  'Bajina Bašta',
  'Batočina',
  'Bečej',
  'Bela Crkva',
  'Bela Palanka',
  'Beočin',
  'Beograd',
  'Blace',
  'Bogatić',
  'Bojnik',
  'Boljevac',
  'Bor',
  'Bosilegrad',
  'Brus',
  'Bujanovac',
  'Čačak',
  'Čajetina',
  'Ćićevac',
  'Čoka',
  'Crna Trava',
  'Ćuprija',
  'Despotovac',
  'Dimitrovgrad',
  'Doljevac',
  'Gadžin Han',
  'Golubac',
  'Gornji Milanovac',
  'Grocka',
  'Inđija',
  'Irig',
  'Ivanjica',
  'Jagodina',
  'Kanjiža',
  'Kikinda',
  'Kladovo',
  'Knić',
  'Knjaževac',
  'Koceljeva',
  'Kosjerić',
  'Kovačica',
  'Kovin',
  'Kragujevac',
  'Kraljevo',
  'Krupanj',
  'Kruševac',
  'Kučevo',
  'Kula',
  'Kuršumlija',
  'Lajkovac',
  'Lapovo',
  'Lazarevac',
  'Lebane',
  'Leskovac',
  'Loznica',
  'Lučani',
  'Majdanpek',
  'Mali Iđoš',
  'Mali Zvornik',
  'Malo Crniće',
  'Medveđa',
  'Merošina',
  'Mionica',
  'Mladenovac',
  'Negotin',
  'Niš',
  'Nova Crnja',
  'Nova Varoš',
  'Novi Bečej',
  'Novi Kneževac',
  'Novi Pazar',
  'Novi Sad',
  'Odžaci',
  'Opovo',
  'Osečina',
  'Obrenovac',
  'Pančevo',
  'Paraćin',
  'Pećinci',
  'Petrovac na Mlavi',
  'Pirot',
  'Plandište',
  'Požarevac',
  'Požega',
  'Preševo',
  'Priboj',
  'Prijepolje',
  'Prokuplje',
  'Rača',
  'Raška',
  'Ražanj',
  'Rekovac',
  'Ruma',
  'Šabac',
  'Sečanj',
  'Senta',
  'Šid',
  'Sjenica',
  'Smederevo',
  'Smederevska Palanka',
  'Sokobanja',
  'Sombor',
  'Sopot',
  'Srbobran',
  'Sremska Mitrovica',
  'Sremski Karlovci',
  'Stara Pazova',
  'Subotica',
  'Surdulica',
  'Svilajnac',
  'Svrljig',
  'Temerin',
  'Titel',
  'Topola',
  'Trgovište',
  'Trstenik',
  'Tutin',
  'Ub',
  'Užice',
  'Valjevo',
  'Varvarin',
  'Velika Plana',
  'Veliko Gradište',
  'Vladičin Han',
  'Vladimirci',
  'Vlasotince',
  'Vračar',
  'Vranje',
  'Vrbas',
  'Vrnjačka Banja',
  'Vršac',
  'Žabalj',
  'Žabari',
  'Žagubica',
  'Zaječar',
  'Žitište',
  'Žitorađa',
  'Zrenjanin',
]
